parameters:
    bsp.adyen.service.class: BSP\AdyenBundle\Service\AdyenService
    bsp.adyen.notification.class: BSP\AdyenBundle\Service\NotificationService

services:
    bsp.adyen.service:
        class: %bsp.adyen.service.class%
        arguments:
            - %bsp.adyen.platform%
            - %bsp.adyen.merchant_account%
            - %bsp.adyen.skin%
            - %bsp.adyen.shared_secret%
            - %bsp.adyen.currency%
            - %bsp.adyen.payment_methods%
            - { username: %bsp.adyen.webservice_username%, password: %bsp.adyen.webservice_password% }
        calls:
            - [ setEventDispatcher, [@event_dispatcher] ]

    bsp.adyen.notification:
        class: %bsp.adyen.notification.class%
        arguments: [ @event_dispatcher, %kernel.logs_dir% ]
